=== Jasonic121/Santorini/frontend/src/resources/xml/gods_grammar.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT cards (god*)>
    <!ELEMENT god (name, description, player, power+)>
            <!ATTLIST god
                id ID #REQUIRED
            >
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT description (#PCDATA)>
        <!ELEMENT player (#PCDATA)>

        <!ELEMENT power (effect, worker, workerpos, timing, constraints, (move | build | malus | win), personalMalus?)>
            <!-- what -->
            <!ELEMENT effect EMPTY>
            <!ATTLIST effect
                    what (build | move | win | malus) #REQUIRED
                    >

            <!-- who -->
            <!ELEMENT worker EMPTY>
                    <!ATTLIST worker 
                        who (default | unmoved) "default"
                    >

            <!-- where -->
            <!ELEMENT workerpos EMPTY>
                    <!ATTLIST workerpos 
                        where (default | ground | middle | top) "default"
                    >

            <!-- when -->
            <!ELEMENT timing EMPTY>
                    <!ATTLIST timing 
                        when (additional | startturn | endturn | default) "default"
                    >

            <!-- why -->
            <!ELEMENT constraints (numadd?)>
                    <!ATTLIST constraints
                        samecell (true | false) "false"
                        notsamecell (true |false) "false"
                        perimcell (true | false) "false"
                        notperimcell (true | false) "false"
                        underitself (true | false) "false"
                    >
                <!ELEMENT numadd (#PCDATA)>

            <!-- how -->

            <!ELEMENT move EMPTY>
                    <!ATTLIST move 
                        type (swap | push | default) "default"
                    >

            <!ELEMENT build EMPTY>
                    <!ATTLIST build
                        type (dome | notdome | default) "default"
                    >

            <!ELEMENT malus (directions?, numturns?)>
                    <!ATTLIST malus
                        type (build | move) #REQUIRED
                        permanent (true | false) "false"
                    >
                <!ELEMENT directions (up?, down?, same?, default?)>
                    <!ELEMENT up EMPTY>
                    <!ELEMENT down EMPTY>
                    <!ELEMENT same EMPTY>
                    <!ELEMENT default EMPTY>
                <!ELEMENT numturns (#PCDATA)>

            <!ELEMENT win EMPTY>
                <!ATTLIST win
                        type (downfromtwo | fivetower | default) "default"
                >

            <!ELEMENT personalMalus (directions?, numturns?)>
                    <!ATTLIST personalMalus
                        type (build | move | default) "default"
                        permanent (true | false) "false"
                    >

=== Jasonic121/Santorini/frontend/src/resources/xml/gods.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cards SYSTEM "gods_grammar.dtd">

<cards>
    <!-- - - - - - - - - - - - - - - - - - - - - - APOLLO - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="APOLLO">
        <name>Apollo</name>
        <description>Your Worker may move into an opponent Worker’s space by forcing their Worker to the space yours just vacated</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="move"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <move type="swap"/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ARTHEMIS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ARTEMIS">
        <name>Artemis</name>
        <description>Your Worker may move one additional time, but not back to its initial space</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="move"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notsamecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <move/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ATHENA - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ATHENA">
        <name>Athena</name>
        <description>If one of your Workers moved up on your last turn, opponent Workers cannot move up this turn</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="malus"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <malus type="move">
                <directions>
                    <up/>
                </directions>
                <numturns>1</numturns>
            </malus>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - ATLAS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="ATLAS">
        <name>Atlas</name>
        <description>Your Worker may build a dome at any level</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="build"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <build type="dome"/>
        </power>
    </god>

    <!-- - - - - - - - - - - - - - - - - - - - - - CHRONUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="CHRONUS">
        <name>Chronus</name>
        <description>You also win when there are at least five Complete Towers on the board</description>
        <player>2</player>
        <power>
            <!-- what -->
            <effect what="win"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <win type="fivetower"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - DEMETER - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="DEMETER">
        <name>Demeter</name>
        <description>Your Worker may build one additional time, but not on the same space</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="build"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notsamecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - HEPHAESTUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="HEPHAESTUS">
        <name>Hephaestus</name>
        <description>Your Worker may build one additional block (not dome) on top of your first block</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="build"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints samecell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build type="notdome"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - HESTIA - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="HESTIA">
        <name>Hestia</name>
        <description>Your Worker may build one additional time, but this cannot be on a perimeter space</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="build"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="additional"/>
            <!-- why -->
            <constraints notperimcell="true">
                <numadd>1</numadd>
            </constraints>
            <!-- how -->
            <build/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - MINOTAUR - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="MINOTAUR">
        <name>Minotaur</name>
        <description>Your Worker may move into an opponent Worker’s space, if their Worker can be forced one space straight backwards to an unoccupied space at any level</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="move"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <move type="push"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - PAN - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PAN">
        <name>Pan</name>
        <description>You also win if your Worker moves down two or more levels</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="win"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="endturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <win type="downfromtwo"/>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - PERSEPHONE - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PERSEPHONE">
        <name>Persephone</name>
        <description> (During your opponent's turn) If possible, at least one Worker must move up this turn</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="malus"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <malus type="move" permanent="true">
                <directions>
                    <down/>
                    <same/>
                </directions>
            </malus>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - POSEIDON - - - - - - - - - - - - - - - - - - - - - - -
    <god id="POSEIDON">
        <name>Poseidon</name>
        <description>If your unmoved Worker is on the ground level, it may build up to three times</description>
        <player>3</player>
        <power>
            <effect what="build"/>
            <!- - who - ->
            <worker who="unmoved"/>
            <!- - where - ->
            <workerpos where="ground"/>
            <!- - when - ->
            <timing when="endturn"/>
            <!- - why - ->
            <constraints>
                <numadd>3</numadd>
            </constraints>
             <!- -how - ->
            <build/>
        </power>
    </god> -->

    <!-- - - -  - - - - - - - - - - - - - - - - - PROMETHEUS - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="PROMETHEUS">
        <name>Prometheus</name>
        <description>If your Worker does not move up, it may build both before and after moving</description>
        <player>3</player>
        <power>
            <!-- what -->
            <effect what="build"/>
            <!-- who -->
            <worker/>
            <!-- where -->
            <workerpos/>
            <!-- when -->
            <timing when="startturn"/>
            <!-- why -->
            <constraints/>
            <!-- how -->
            <build/>
            <personalMalus type="move">
                <directions>
                    <up/>
                </directions>
                <numturns>1</numturns>
            </personalMalus>
        </power>
    </god>

    <!-- - - -  - - - - - - - - - - - - - - - - - TRITON - - - - - - - - - - - - - - - - - - - - - - - - -->
    <god id="TRITON">
        <name>Triton</name>
